// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


float cloudFrequency;
float cloudPWM;
float cloudVoltage;

void initProperties(){

  ArduinoCloud.addProperty(cloudFrequency, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloudPWM, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloudVoltage, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
